#\DeclareLyXModule{ColorCode}
#\DeclareCategory{Boxes}
#DescriptionBegin
#Nice color boxes for code wrapping.
#Based on original module by Jürgen Spitzmüller and Uwe Stöhr.
#DescriptionEnd
#
#Author: Vadim Zyamalov <vadim@zyamalov.ru>

Format 104

Input colorcode_colors.inc

InsetLayout Flex:Colorcode
	LyXType		custom
	LatexType   Environment
	Decoration	classic
	LabelString	Colorcode
	LatexName	colorcode
	Argument 1
	  LabelString	"Language"
	  Tooltip	"Select inner programming language"
	  Mandatory	1
	  DefaultArg	"R"
	  AutoInsert	1
	EndArgument
	LabelFont
	  Family	Roman
	  Color		textlabel1
	EndFont
	ResetsFont	0
	Requires	tcolorbox
	Preamble
\newtcolorbox{colorcode}[1]{%
	enhanced jigsaw,%
	attach boxed title to top text left={yshift=-3mm,yshifttext=-1mm},%
	colframe=\bbp@fg{#1},%
	coltitle=\bbp@fg{#1},%
	colback=\bbp@bg{#1},%
	colbacktitle=\bbp@bg{#1},%
	title={\texttt{\bbp@name{#1}}}%
}
	EndPreamble
	MultiPar	0
End

InsetLayout Flex:Coloroutput
	CopyStyle	Flex:Colorcode
	LabelString	Coloroutput
	LatexName	colorout
	LabelFont
	  Family	Roman
	  Color		textlabel2
	EndFont
	Preamble
\newtcolorbox{colorout}[1]{%
	enhanced jigsaw,%
	colframe=\bbp@fg{#1},%
	colback=\bbp@bg{#1},%
}
	EndPreamble
End
