#\DeclareLyXModule{Tasks Environment}
#\DeclareCategory{Academic Field Specifics}
#DescriptionBegin
#Defines tasks environment with the tasks package.
#DescriptionEnd

Format 104

Counter tasksi
	GuiName              Tasks
    Within               exercise
	LabelString          "\alph{tasksi}"
	PrettyFormat         "##"
End

Style Tasks
    Category              Reasoning
    Margin                Dynamic
    LatexType             Item_Environment
    LatexName             tasks
    IsAutoNestedBy
      Exercise
    EndIsAutoNestedBy
    Argument 1
		LabelString   "Itemize Options"
		Tooltip       "Optional arguments for this list (see enumitem manual)"
	EndArgument
    LabelType             Enumerate
    LabelCounter          tasks
    LabelIndent           xx
    LabelSep              xx
    ParIndent             MMM
    Align                 Block
    AlignPossible         Block, Left
    Font
        Shape             Up
        Size              Normal
    EndFont
    LabelFont
        Shape             Up
        Series            Bold
    EndFont
    RefPrefix             task
    Requires              enumitem
    Preamble
        \newlist{tasks}{enumerate}{1}
        \setlist[tasks,1]{
        nosep,
        labelindent=\parindent,
        leftmargin=*,
        label=\bfseries\asbuk*.,
        ref=\theexercise\asbuk*
    }
    EndPreamble
End