#\DeclareLyXModule{Exercise Environments (Continuous)}
#\DeclareCategory{Academic Field Specifics}
#DescriptionBegin
#Defines exercise environments with the xsim package.
#Based on the post by tush (License - CC BY-SA 4.0):
#https://tex.stackexchange.com/a/632209.
#DescriptionEnd

Format 60

Input tasks.module

AddToPreamble
  \usepackage{xsim}

  \DeclareExerciseEnvironmentTemplate{runin}{%
    \par%
    \noindent
    \textbf{\XSIMmixedcase{\GetExerciseName}~\GetExerciseProperty{counter}}%
    \GetExercisePropertyT{subtitle}{ \textit{#1}} % <<< notice the space
    \IfInsideSolutionF{%
      \GetExercisePropertyT{points}{%
        \marginpar{%
          \printgoal{\PropertyValue}%
          \GetExercisePropertyT{bonus-points}{+\printgoal{\PropertyValue}}%
          \,\IfExerciseGoalSingularTF{points}
          {\XSIMtranslate{point}}
          {\XSIMtranslate{points}}%
        }%
      }%
    }%
  }
  {}
 
  \xsimsetup{
    exercise/template=runin,
    solution/template=runin
  }

  \DeclareExerciseTranslation{Russian}{exercise}{№}
  \DeclareExerciseTranslation{Russian}{exercises}{упражнения}
  \DeclareExerciseTranslation{Russian}{question}{вопрос}
  \DeclareExerciseTranslation{Russian}{questions}{вопросы}
  \DeclareExerciseTranslation{Russian}{solution}{решение №}
  \DeclareExerciseTranslation{Russian}{solutions}{решения}
  \DeclareExerciseTranslation{Russian}{point-abbr}{б.}
  \DeclareExerciseTranslation{Russian}{point}{балл}
  \DeclareExerciseTranslation{Russian}{points}{баллы}
  \DeclareExerciseTranslation{Russian}{reached}{получено}
  \DeclareExerciseTranslation{Russian}{default-heading}{Решения упражнений}
  \DeclareExerciseTranslation{Russian}{collection-heading}{Упражнения}
  \DeclareExerciseTranslation{Russian}{per-section-heading}{Решения упражнений раздела\nobreakspace \ExerciseSection}
  \DeclareExerciseTranslation{Russian}{per-chapter-heading}{Решения упражнений главы\nobreakspace \ExerciseChapter}
EndPreamble

Counter exercise
  PrettyFormat   "##"
  LabelString    "\arabic{exercise}"
End

Style ExSolCommon
  Margin                Dynamic
  LatexType             Environment
  ParagraphGroup        1
  NextNoIndent          1
  ResetArgs             1
  KeepEmpty             1
  Argument 1
    LabelString   "Optional parameter"
    Decoration    Minimalistic
  EndArgument
  AutoNests
    Standard,Itemize,Enumerate,Description,Tasks
  EndAutoNests
  ParIndent             MMM
  ParSep                0.5
  Parskip               1
  Align                 Block
  AlignPossible         Block,Left,Right,Center
  BottomSep             2.0
  LabelSep              xx
  LabelType             Static
  Font
    Shape               Up
    Size                Normal
  EndFont
  LabelFont
    Shape               Up
    Series              Bold
  EndFont
  Requires              xsim
End

Style Exercise
  CopyStyle             ExSolCommon
  Category              Reasoning
  LatexName             exercise
  AddToToc              Exercises
  IsTocCaption          1
  LabelCounter          exercise
  LabelString           "Ex. \theexercise"
  RefPrefix             ex:
End

Style Solution
  CopyStyle             ExSolCommon
  Category              Reasoning
  LatexName             solution
  LabelString           "Sol. \theexercise"
  RefPrefix             sol:
End

NoStyle ExSolCommon