#\DeclareLyXModule{Chapter-wise Exercise Environments}
#\DeclareCategory{Academic Field Specifics}
#DescriptionBegin
#Defines exercise environments with the xsim package.
#Based on the post by tush (License - CC BY-SA 4.0):
#https://tex.stackexchange.com/a/632209.
#DescriptionEnd

Format 60

Input tasks.module

AddToPreamble
  \usepackage{xsim}
  \xsimsetup{exercise/within={chapter}}

  \DeclareExerciseEnvironmentTemplate{runin}{%
    \par%
    \noindent
    \textbf{\XSIMmixedcase{\GetExerciseName}~\GetExerciseProperty{counter}}%
    \GetExercisePropertyT{subtitle}{ \textit{#1}} % <<< notice the space
    \IfInsideSolutionF{%
      \GetExercisePropertyT{points}{%
        \marginpar{%
          \printgoal{\PropertyValue}%
          \GetExercisePropertyT{bonus-points}{+\printgoal{\PropertyValue}}%
          \,\IfExerciseGoalSingularTF{points}
          {\XSIMtranslate{point}}
          {\XSIMtranslate{points}}%
        }%
      }%
    }%
  }
  {}
 
  \xsimsetup{
    exercise/template=runin,
    solution/template=runin
  }

  \DeclareExerciseTranslation{Russian}{exercise}{№}
  \DeclareExerciseTranslation{Russian}{exercises}{упражнения}
  \DeclareExerciseTranslation{Russian}{question}{вопрос}
  \DeclareExerciseTranslation{Russian}{questions}{вопросы}
  \DeclareExerciseTranslation{Russian}{solution}{решение №}
  \DeclareExerciseTranslation{Russian}{solutions}{решения}
  \DeclareExerciseTranslation{Russian}{point-abbr}{б.}
  \DeclareExerciseTranslation{Russian}{point}{балл}
  \DeclareExerciseTranslation{Russian}{points}{баллы}
  \DeclareExerciseTranslation{Russian}{reached}{получено}
  \DeclareExerciseTranslation{Russian}{default-heading}{Решения упражнений}
  \DeclareExerciseTranslation{Russian}{collection-heading}{Упражнения}
  \DeclareExerciseTranslation{Russian}{per-section-heading}{Решения упражнений раздела\nobreakspace \ExerciseSection}
  \DeclareExerciseTranslation{Russian}{per-chapter-heading}{Решения упражнений главы\nobreakspace \ExerciseChapter}
EndPreamble

Counter exercise
  Within         chapter
  PrettyFormat   ##
  LabelString    \thechapter.\theexercise
End

Style Exercise
  Category              Reasoning
  Margin                Dynamic
  LatexType             Environment
  LatexName             exercise
  ParagraphGroup        1
  NextNoIndent          1
  ResetArgs             1
  Argument 1
    LabelString   "Optional parameter"
    Decoration    Minimalistic
  EndArgument
  AddToToc              Exercises
  IsTocCaption          1
  AutoNests
    Standard,Itemize,Enumerate,Description,Tasks
  EndAutoNests
  ParIndent             MMM
  ParSep                0.5
  Parskip               1
  Align                 Block
  AlignPossible         Block,Left,Right,Center
  BottomSep             1.0
  LabelSep              xx
  LabelType             Static
  LabelCounter          exercise
  LabelString           "Ex. \theexercise"
  Font
    Shape               Up
    Size                Normal
  EndFont
  LabelFont
    Shape               Up
    Series              Bold
  EndFont
  RefPrefix             ex:
  Requires              xsim
End

Style Solution
  CopyStyle             Exercise
  LatexName             solution
  LabelString           "Sol. \theexercise"
  RefPrefix             sol:
  Requires              xsim
End
